# Generated by Django 3.1.6 on 2021-02-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResultRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resultidmodel')),
            ],
        ),
    ]
